import type { JobViewData } from "../contracts/job-view";

export const referenceJobView: JobViewData = {
  id: "196794136",
  title: "Senior React Engineer",
  companyName: "Capitec",
  location: "Cape Town, South Africa",
  datePostedLabel: "20 July 2022",
  employmentType: "Full Time",
  salaryLabel: "Market Related",
  seniorityLevel: "Mid / Senior",
  experienceRangeLabel: "3 years - 5 years",
  skills: [
    "React",
    "Development",
    "Front End",
    "Javascript",
    "Testing",
    "Code Refactoring",
    "Software Development"
  ],
  industries: [
    "Development",
    "Banking",
    "Recruitment",
    "Marketing",
    "Software",
    "Artificial Intelligence",
    "Human Resources"
  ],
  jobDescriptionHtml: [
    "<p>React Engineer - AI-Native Frontend | Build the Future of Professional Platforms</p>",
    "<p>Ditto is building the next generation of recruitment and professional platforms, used by millions each month. We help staffing firms and hiring teams find, manage, and place top candidates with smart, beautiful software.</p>",
    "<p>Now we're launching something new. AI-native. Agent-driven. Stealth.</p>",
    "<p>We're looking for a React Engineer who understands that modern frontend is no longer just UI. It's automation, orchestration, agent interaction, and intelligent workflows.</p>",
    "<p>If you want to build interfaces that sit on top of AI agents, automate real work, and ship fast with serious scale from day one, keep reading.</p>",
    "<p><strong>What You'll Do</strong></p>",
    "<ul>",
    "<li>Build modern, responsive UIs powered by AI-driven workflows</li>",
    "<li>Design frontends that interact with agents, automations, and intelligent back-end services</li>",
    "<li>Integrate AI features into real product flows, not gimmicks</li>",
    "<li>Work closely with product and design to build fast, intuitive, opinionated experiences</li>",
    "<li>Write clean, scalable components that support dynamic, AI-generated content</li>",
    "<li>Implement automated test scripts and validation flows for AI interactions</li>",
    "<li>Help define how our frontend talks to orchestration layers, APIs, and agent systems</li>",
    "<li>Own performance, reliability, and developer experience</li>",
    "</ul>",
    "<p><strong>Must-Haves</strong></p>",
    "<ul>",
    "<li>Strong React + Next.js experience</li>",
    "<li>Deep understanding of modern SPA architecture</li>",
    "<li>REST APIs + JSON fluency</li>",
    "<li>Node.js + NPM</li>",
    "<li>Git (you're comfortable in real-world team repos)</li>",
    "<li>Experience shipping real production software</li>",
    "<li>Comfort working in fast-moving environments</li>",
    "</ul>",
    "<p><strong>Strong Bonus If You've Worked With</strong></p>",
    "<ul>",
    "<li>AI agents, automation workflows, or LLM-powered features</li>",
    "<li>Prompt orchestration patterns</li>",
    "<li>Tool-calling flows or agent frameworks</li>",
    "<li>Automated testing (Playwright, Cypress, Jest)</li>",
    "<li>Scriptable workflows (Bash, CLI tools, automation tooling)</li>",
    "<li>Cursor or AI-assisted coding tools</li>",
    "<li>Performance tuning and caching strategies</li>",
    "<li>Design systems and component libraries</li>",
    "<li>Writing documentation that engineers actually read</li>",
    "</ul>",
    "<p>If you've built interfaces that sit on top of AI, orchestration layers, or automation systems - that's a big plus.</p>",
    "<p><strong>The Type of Engineer We Want</strong></p>",
    "<p>You think in systems. You don't panic when something becomes dynamic or unpredictable. You understand that AI outputs require guardrails, validation, and good UX. You care about performance and elegance. You ship.</p>",
    "<p><strong>Why Join Ditto?</strong></p>",
    "<ul>",
    "<li>Ground-floor on a major AI-native product</li>",
    "<li>Millions of users at launch</li>",
    "<li>Real ownership. No bureaucracy.</li>",
    "<li>Fast shipping cycles</li>",
    "<li>Smart, opinionated builders</li>",
    "<li>We build serious infrastructure. Not corporate fluff.</li>",
    "</ul>",
    "<p>We're rethinking how professionals present themselves, connect, and build identity online.</p>",
    "<p>If this feels like your kind of problem to solve, let's talk - you'll be part of something fun. We build cool shit, not corporate fluff.</p>"
  ].join(""),
  companyDescriptionHtml:
    "<p>Capitec Bank is a South African retail bank focused on simplified banking, accessible digital tools, and client-first financial services. With a strong national presence and a digital-first service model, it serves personal and business clients through branches, mobile banking, and a streamlined product offering.</p>",
  companyCoverImageUrl: "/company/standard-bank-group-cover.jpeg",
  companyLogoUrl: "/company/capitec-bank-logo.jpg",
  companyUrl: "https://www.capitecbank.co.za",
  applyUrl: "https://www.ditto.jobs/application?job_id=196794136",
  recommendedJobs: null
};
